### ISSUE TITLE
ssl: connect by IP (one domain) verify by Host header (another domain)

### ISSUE THREAD

**Issue by bscheshir** [DaKaZ/esp8266-restclient#3]
How about this case:

server nginx config
```conf
server {
    server_name api.dev;
}
```
https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/d7303e2d0c951cc44516c55950ddc6dc2f9f4d41/nginx-conf/nginx.conf#L108

server certificate `CN = api.dev` or `[ext]
subjectAltName = DNS:api.dev,DNS:*.api.dev`

https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blame/api/docs/about-api-ssl.md#L113

connect to server use IP of host machine and verify by `hostHeader`, not by `host`
```ino
const char* host = "192.168.1.39";
const char* hostHeader = "api.dev";
const int httpsPort = 8082;
String url = "/v1/feedback/create";
// Use web browser to view and copy SHA1 fingerprint of the certificate or use
// openssl x509 -in server.crt -fingerprint 
const char* fingerprint = "A1 1F 18 32 A7 2C CE 2B 74 F8 0E 35 A7 11 16 11 7F 61 22 C9";
...
setup(){
...
  //connect to host
  Serial.print("connecting to ");
  Serial.println((String)host);
  if (!espClient.connect(host, httpsPort)) {
    Serial.println("connection failed");
    return;
  }


  if (espClient.verify(fingerprint, hostHeader)) {
    Serial.println("certificate matches");
  } else {
    Serial.println("certificate doesn't match");
  }
  
  Serial.print("requesting URL: ");
  Serial.println(url);

  espClient.print(String("POST ") + url + " HTTP/1.1\r\n" +
               "Host: " + hostHeader + "\r\n" +
               "User-Agent: MP3ESP8266\r\n" +
               "Connection: close\r\n\r\n");

}
```
https://github.com/bscheshir/esp8266-mp3-web-server/blob/b1f0231c3f8681c39d040d99b39d200282ad1ab3/WiFiWebServerMP3.ino#L40-L46
https://github.com/bscheshir/esp8266-mp3-web-server/blob/b1f0231c3f8681c39d040d99b39d200282ad1ab3/WiFiWebServerMP3.ino#L185-L206

I think about use your library, but
in this library I can see only equials `sslClient.verify(...,host)` ; `sslClient.connect(host,...)` 

https://github.com/DaKaZ/esp8266-restclient/blob/4e2069f837328d4647b6cbab88f1adc7e0e03367/RestClient.cpp#L161-L167

**Comment by DaKaZ** [comment]
@ccfiel I looked at your commit and I don't know why you wouldn't want to return an error if the certs don't match (line 171).  Thats the whole point of this library... to make sure it's a secure connection.  Secondly, I am 99% sure that the internals to `connect` will do a DNS lookup on the host name, so doing that in the rest client is redundant.  

I think the issue here is that the certificate uses the alternative name.  I am not complete certain, but the fix you show would not be a valid one.  I open to other PRs through if you come up one.
